### ISSUE TITLE
Error: Cannot find module 'electron-config'

### ISSUE THREAD

**Issue by slikie** [djyde/sinatine#4]
环境：macOS 10.12.3 
brew install yarn
然后
按给定的办法build的

> sinatine@0.0.1 app /Users/rility/git/sinatine
> ENV=dev electron app/

App threw an error during load
Error: Cannot find module 'electron-config'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/rility/git/sinatine/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rility/git/sinatine/app/config.js:1:171)
    at Object.<anonymous> (/Users/rility/git/sinatine/app/config.js:13:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
^C

**Comment by slikie** [comment]
然后 安全验证没有办法加载出来。其他客户端正常。
![screen shot 2017-03-24 at 10 16 27 pm](https://cloud.githubusercontent.com/assets/13197246/24298001/a5ccc7e2-10df-11e7-9217-646fd8d0e36d.png)

**Comment by djyde** [comment]
要在 `app/` 里面也 `yarn` 一下
